### ISSUE TITLE
插入图片问题

### ISSUE THREAD

**Issue by smartnaive** [tianhaoo/Soochow-University-Thesis-Overleaf-LaTeX-Template#1]
你好啊，想请问一下，我在模板里插入图片后，图片标题底下的留白长短不一，应该怎么样调整呀

**Comment by tianhaoo** [comment]
> 你好啊，想请问一下，我在模板里插入图片后，图片标题底下的留白长短不一，应该怎么样调整呀

latex代码和截图贴一下看看

**Comment by smartnaive** [comment]
> 
谢谢回复，应该是自动排版排的问题，我调整了前后文图片的大小后，留白就自动缩短了。
