### ISSUE TITLE
如何引用参考文献

### ISSUE THREAD

**Issue by Vpredictor** [tianhaoo/Soochow-University-Thesis-Overleaf-LaTeX-Template#2]
在main.tex和分章节中使用
```
\bibliographystyle{unsrt}
\bibliography{reference}
```
都无法正确引用文献

**Comment by Vpredictor** [comment]
已解决，用\cite而不是\ref引用参考文献。

**Comment by REAL-Madrid01** [comment]
1. Remove \bibliographystyle{sudacis or something else} in cls.file
2. Add \bibliographystyle{plain} in main.tex before \document start
3. Link \bibliography{reference} with your reference.bib (which means add \bibliography{reference} in place u want in main.tex)
4. Using \cite{keyword of article or book...} in content/or u say chapter, or bib file wont work they are spare when u dont cite them!
5. Compile your main.tex using F6 F8 F6 F6, four steps and u will see it works.
PS (useful link below to help u better understand each step :D)
  https://blog.csdn.net/weixin_41692282/article/details/103198609
